name: Deploy Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Generate documentation
      run: npm run docs
      
    - name: Check if Pages is enabled
      id: check-pages
      run: |
        # Check if Pages is enabled by trying to configure it
        echo "Checking GitHub Pages configuration..."
        if curl -s -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
           "https://api.github.com/repos/${{ github.repository }}/pages" | grep -q "Not Found"; then
          echo "pages_enabled=false" >> $GITHUB_OUTPUT
          echo "GitHub Pages is not enabled for this repository"
        else
          echo "pages_enabled=true" >> $GITHUB_OUTPUT
          echo "GitHub Pages is enabled"
        fi
      continue-on-error: true
      
    - name: Setup Pages
      if: steps.check-pages.outputs.pages_enabled == 'true'
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      if: steps.check-pages.outputs.pages_enabled == 'true'
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs'
        
    - name: Deploy to GitHub Pages
      if: steps.check-pages.outputs.pages_enabled == 'true'
      id: deployment
      uses: actions/deploy-pages@v4
      
    - name: Comment PR (Pages enabled)
      if: github.event_name == 'pull_request' && steps.check-pages.outputs.pages_enabled == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Documentation has been generated and deployed to: https://${context.repo.owner}.github.io/${context.repo.repo}/`
          })
          
    - name: Comment PR (Pages not enabled)
      if: github.event_name == 'pull_request' && steps.check-pages.outputs.pages_enabled == 'false'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Documentation has been generated successfully. To enable GitHub Pages deployment, go to repository Settings > Pages and configure GitHub Actions as the source.`
          })
          
    - name: Success message
      run: |
        if [ "${{ steps.check-pages.outputs.pages_enabled }}" = "true" ]; then
          echo "Documentation deployed successfully to GitHub Pages"
        else
          echo "Documentation generated successfully. GitHub Pages is not enabled for this repository."
          echo "To enable Pages: Go to repository Settings > Pages > Source: GitHub Actions"
        fi 